// Константы
export const GET_FILES_REQUEST = 'GET_FILES_REQUEST';
export const GET_FILES_SUCCESS = 'GET_FILES_SUCCESS';
export const GET_FILES_FAIL = 'GET_FILES_FAIL';

export const GET_USER_FILES_REQUEST = 'GET_USER_FILES_REQUEST';
export const GET_USER_FILES_SUCCESS = 'GET_USER_FILES_SUCCESS';
export const GET_USER_FILES_FAIL = 'GET_USER_FILES_FAIL';

export const ADD_FILES_REQUEST = 'ADD_FILES_REQUEST';
export const ADD_FILES_SUCCESS = 'ADD_FILES_SUCCESS';
export const ADD_FILES_FAIL = 'ADD_FILES_FAIL';
export const ADD_FILES_RESET = 'ADD_FILES_RESET';

export const DETAIL_FILES_REQUEST = 'DETAIL_FILES_REQUEST';
export const DETAIL_FILES_SUCCESS = 'DETAIL_FILES_SUCCESS';
export const DETAIL_FILES_FAIL = 'DETAIL_FILES_FAIL';

export const UPDATE_FILES_REQUEST = 'UPDATE_FILES_REQUEST';
export const UPDATE_FILES_SUCCESS = 'UPDATE_FILES_SUCCESS';
export const UPDATE_FILES_FAIL = 'UPDATE_FILES_FAIL';
export const UPDATE_FILES_RESET = 'UPDATE_FILES_RESET';

export const DELETE_FILES_REQUEST = 'DELETE_FILES_REQUEST';
export const DELETE_FILES_SUCCESS = 'DELETE_FILES_SUCCESS';
export const DELETE_FILES_FAIL = 'DELETE_FILES_FAIL';